In [1]:
import pandas as pd

from utils.preprocess import encode, load_and_evaluate_model

from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

import warnings
warnings.simplefilter('ignore')

In [2]:
datapath = '../data/'

df = pd.read_csv(datapath+'kddcup.data.csv')
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,Y
0,0,0,0,0,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0
1,0,0,0,0,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0,0
2,0,0,0,0,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0,0
3,0,0,0,0,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0,0
4,0,0,0,0,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,0,0,0,212,2288,0,0,0,0,...,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0,0
4898427,0,0,0,0,219,236,0,0,0,0,...,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0,0
4898428,0,0,0,0,218,3610,0,0,0,0,...,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0,0
4898429,0,0,0,0,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0,0
4898430,0,0,0,0,219,1098,0,0,0,0,...,255,1.0,0.0,0.14,0.05,0.0,0.01,0.0,0.0,0

In [3]:
X = df.drop(columns=['Y'])
Y = df['Y']

scaler = Normalizer().fit(X)
X = scaler.transform(X)

In [4]:
df = pd.DataFrame(X, columns=df.drop(columns=['Y']).columns)
df['Y'] = Y
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,Y
0,0.0,0.0,0.0,0.0,0.004770,0.999989,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.035754,0.999360,0.0,0.0,0.0,0.0,...,0.000221,0.000221,0.0,0.000221,0.000000,0.0,0.000000,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.188728,0.982025,0.0,0.0,0.0,0.0,...,0.001599,0.000800,0.0,0.000400,0.000000,0.0,0.000000,0.0,0.0,0
3,0.0,0.0,0.0,0.0,0.113918,0.993487,0.0,0.0,0.0,0.0,...,0.001467,0.000489,0.0,0.000161,0.000000,0.0,0.000000,0.0,0.0,0
4,0.0,0.0,0.0,0.0,0.441255,0.897281,0.0,0.0,0.0,0.0,...,0.007385,0.001846,0.0,0.000462,0.000000,0.0,0.000000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0.0,0.0,0.0,0.0,0.091690,0.989563,0.0,0.0,0.0,0.0,...,0.110288,0.000433,0.0,0.000143,0.000022,0.0,0.000004,0.0,0.0,0
4898427,0.0,0.0,0.0,0.0,0.531456,0.572711,0.0,0.0,0.0,0.0,...,0.618819,0.002427,0.0,0.000607,0.000121,0.0,0.000024,0.0,0.0,0
4898428,0.0,0.0,0.0,0.0,0.060126,0.995664,0.0,0.0,0.0,0.0,...,0.070331,0.000276,0.0,0.000055,0.000014,0.0,0.000003,0.0,0.0,0
4898429,0.0,0.0,0.0,0.0,0.171165,0.964462,0.0,0.0,0.0,0.0,...,0.199301,0.000782,0.0,0.000133,0.000039,0.0,0.000008,0.0,0.0,0
4898430,0.0,0.0,0.0,0.0,0.190713,0.956178,0.0,0.0,0.0,0.0,...,0.222063,0.000871,0.0,0.000122,0.000044,0.0,0.000009,0.0,0.0,0

In [5]:
df_80,fold_1=train_test_split(df,test_size=0.2,stratify=df['Y'],random_state=42)

In [6]:
df_80['Y'].value_counts()/len(df_80)

3    0.573221
2    0.218849
0    0.198590
1    0.009339
Name: Y, dtype: float64

In [7]:
fold_1['Y'].value_counts()/len(fold_1)

3    0.573222
2    0.218849
0    0.198590
1    0.009339
Name: Y, dtype: float64

In [8]:
df_40,df_40_b=train_test_split(df_80,test_size=0.5,stratify=df_80['Y'],random_state=42)
fold_2,fold_3=train_test_split(df_40,test_size=0.5,stratify=df_40['Y'],random_state=42)
fold_4,fold_5=train_test_split(df_40_b,test_size=0.5,stratify=df_40_b['Y'],random_state=42)

In [9]:
folds=[fold_1,fold_2,fold_3,fold_4,fold_5]

In [10]:
for fold in folds:
    X, y = fold.drop(columns=['Y']), fold['Y']
    load_and_evaluate_model('tanh_dnn.hdf5', X, y)

Evaluating tanh_dnn:
957/957 [==============================] - 2s 1ms/step - loss: 0.0519 - accuracy: 0.9891
              precision    recall  f1-score   support

           0       0.98      0.99      0.99    194556
           1       0.00      0.00      0.00      9149
           2       0.97      1.00      0.99    214404
           3       1.00      1.00      1.00    561578

    accuracy                           0.99    979687
   macro avg       0.74      0.75      0.74    979687
weighted avg       0.98      0.99      0.98    979687

Evaluating tanh_dnn:
957/957 [==============================] - 1s 1ms/step - loss: 0.0523 - accuracy: 0.9890
              precision    recall  f1-score   support

           0       0.98      0.99      0.99    194556
           1       0.00      0.00      0.00      9149
           2       0.97      1.00      0.99    214404
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.74      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_dnn:
957/957 [==============================] - 2s 2ms/step - loss: 0.0521 - accuracy: 0.9890
              precision    recall  f1-score   support

           0       0.98      0.99      0.99    194556
           1       0.00      0.00      0.00      9150
           2       0.97      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.74      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_dnn:
957/957 [==============================] - 2s 1ms/step - loss: 0.0522 - accuracy: 0.9890
              precision    recall  f1-score   support

           0       0.98      0.99      0.99    194556
           1       0.00      0.00      0.00      9150
           2       0.97      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.74      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_dnn:
957/957 [==============================] - 2s 1ms/step - loss: 0.0521 - accuracy: 0.9890
              precision    recall  f1-score   support

           0       0.98      0.99      0.99    194557
           1       0.00      0.00      0.00      9149
           2       0.97      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.74      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

In [10]:
for fold in folds:
    X, y = fold.drop(columns=['Y']), fold['Y']
    load_and_evaluate_model('tanh_cnn.hdf5', X, y)

Evaluating tanh_cnn:
957/957 [==============================] - 3s 2ms/step - loss: 0.0305 - accuracy: 0.9921
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    194556
           1       0.82      0.29      0.42      9149
           2       0.98      1.00      0.99    214404
           3       1.00      1.00      1.00    561578

    accuracy                           0.99    979687
   macro avg       0.95      0.82      0.85    979687
weighted avg       0.99      0.99      0.99    979687

Evaluating tanh_cnn:
957/957 [==============================] - 2s 2ms/step - loss: 0.0310 - accuracy: 0.9920
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    194556
           1       0.81      0.28      0.41      9149
           2       0.98      1.00      0.99    214404
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.94      0.82      0.85    979686
weighted avg       0.99      0.99      0.99    979686

Evaluating tanh_cnn:
957/957 [==============================] - 2s 2ms/step - loss: 0.0309 - accuracy: 0.9921
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    194556
           1       0.83      0.29      0.43      9150
           2       0.98      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.95      0.82      0.85    979686
weighted avg       0.99      0.99      0.99    979686

Evaluating tanh_cnn:
957/957 [==============================] - 2s 2ms/step - loss: 0.0309 - accuracy: 0.9921
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    194556
           1       0.83      0.28      0.41      9150
           2       0.98      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.95      0.82      0.85    979686
weighted avg       0.99      0.99      0.99    979686

Evaluating tanh_cnn:
957/957 [==============================] - 2s 2ms/step - loss: 0.0307 - accuracy: 0.9922
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    194557
           1       0.83      0.28      0.42      9149
           2       0.98      1.00      0.99    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.95      0.82      0.85    979686
weighted avg       0.99      0.99      0.99    979686

In [11]:
for fold in folds:
    X, y = fold.drop(columns=['Y']), fold['Y']
    load_and_evaluate_model('tanh_lstm.hdf5', X, y)

Evaluating tanh_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.0553 - accuracy: 0.9870
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    194556
           1       0.00      0.00      0.00      9149
           2       0.98      0.99      0.98    214404
           3       1.00      1.00      1.00    561578

    accuracy                           0.99    979687
   macro avg       0.73      0.75      0.74    979687
weighted avg       0.98      0.99      0.98    979687

Evaluating tanh_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.0556 - accuracy: 0.9870
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    194556
           1       0.00      0.00      0.00      9149
           2       0.98      0.99      0.98    214404
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.0560 - accuracy: 0.9868
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    194556
           1       0.00      0.00      0.00      9150
           2       0.98      0.99      0.98    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.0555 - accuracy: 0.9870
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    194556
           1       0.00      0.00      0.00      9150
           2       0.98      0.99      0.98    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_lstm:
957/957 [==============================] - 3s 3ms/step - loss: 0.0557 - accuracy: 0.9869
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    194557
           1       0.00      0.00      0.00      9149
           2       0.98      0.99      0.98    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.75      0.74    979686
weighted avg       0.98      0.99      0.98    979686

In [12]:
for fold in folds:
    X, y = fold.drop(columns=['Y']), fold['Y']
    load_and_evaluate_model('tanh_cnn_lstm.hdf5', X, y)

Evaluating tanh_cnn_lstm:
957/957 [==============================] - 3s 3ms/step - loss: 0.1414 - accuracy: 0.9850
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    194556
           1       0.00      0.00      0.00      9149
           2       0.95      1.00      0.97    214404
           3       1.00      1.00      1.00    561578

    accuracy                           0.99    979687
   macro avg       0.73      0.74      0.74    979687
weighted avg       0.98      0.99      0.98    979687

Evaluating tanh_cnn_lstm:
957/957 [==============================] - 4s 4ms/step - loss: 0.1417 - accuracy: 0.9848
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    194556
           1       0.00      0.00      0.00      9149
           2       0.95      1.00      0.97    214404
           3       1.00      1.00      1.00    561577

    accuracy                           0.98    979686
   macro avg       0.73      0.74      0.74    979686
weighted avg       0.98      0.98      0.98    979686

Evaluating tanh_cnn_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.1422 - accuracy: 0.9849
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    194556
           1       0.00      0.00      0.00      9150
           2       0.95      1.00      0.97    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.98    979686
   macro avg       0.73      0.74      0.74    979686
weighted avg       0.98      0.98      0.98    979686

Evaluating tanh_cnn_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.1412 - accuracy: 0.9850
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    194556
           1       0.00      0.00      0.00      9150
           2       0.95      1.00      0.97    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.74      0.74    979686
weighted avg       0.98      0.99      0.98    979686

Evaluating tanh_cnn_lstm:
957/957 [==============================] - 4s 3ms/step - loss: 0.1408 - accuracy: 0.9850
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    194557
           1       0.00      0.00      0.00      9149
           2       0.95      1.00      0.97    214403
           3       1.00      1.00      1.00    561577

    accuracy                           0.99    979686
   macro avg       0.73      0.74      0.74    979686
weighted avg       0.98      0.99      0.98    979686